## Know Your Soil
<!-- # ```{r echo=FALSE, background=TRUE, message=FALSE} -->
<!-- # googledrive::drive_find("PFP Lesson 1 — The People of Corn — Short Session", type = "document") -->
<!-- # tf <- tempfile(fileext = ".odt") -->
<!-- # googledrive::drive_download(file = googledrive::as_id("1NoIdN_dIm4nnQc8767DFB-O-AfxL7mK2Y6xz1BOPr5o"), -->
<!-- #                             path = tf) -->
<!-- # system(stringr::str_c("pandoc -s ",tf," -t markdown -o lessons/PFP_Lesson-2_Farming-Through-Drought_Short.md")) -->
<!-- # system("sed -i '' 's/> //g' lessons/PFP_Lesson-2_Farming-Through-Drought_Short.md") -->
<!-- # ``` -->

<!-- tabsets -->
<script>
$(document).ready(function() {
window.buildTabsets("TOC");
});

</script>

Crop health is directly related to the health of soils. This lesson teaches students to witness and understand that soil can store water for the needs of humans and plants, and invites them to practice applying modern soil testing techniques. Download the PDF versions of the [long](./lessons/PFP_Lesson-3_Know-Your-Soil_Long.pdf) or [short](./lessons/PFP_Lesson-3_Know-Your-Soil_Short.pdf) sessions.

### {- .tabset .tabset-fade}

#### Preparation {-}
##### Grades {-}
6, 7, 8

This lesson can be taught to each middle school grade with increasing
complexity and detail.

##### Season {-}
Spring (best), Fall (next best), Summer (possible)

##### Objectives {-}

*   Understand the connections between the health of the soil and the health of plant communities.
*   Witness and understand that soil can store water for the needs of humans and plants.
*   Practice applying modern soil testing techniques.
*   Practice applying Puebloan agricultural practices.

##### Key Terms {-}

*   Dryland farming
*   Evapotranspiration 
*   Site selection
*   Drought-resilient
*   Indicator plants
*   Check dam
*   Dust mulch
*   Runoff
*   Erosion

##### Materials and Tools {-}

*   Whiteboard and markers
*   Water cycle diagram to print or project: search Google Images for "Water Cycle 6th grade" for many options.
*   Article: Wall, D. and Masayesva, V. (2004). People of the Corn:
    Teachings in Hopi traditional agriculture, spirituality, and
    sustainability. *The American Indian Quarterly*, 28(3--4):435--453.
    <br>(Available [here](./lessons/Wall2004_People_of_the_Corn.pdf) for non-commercial
    purposes.)
*   Colorado Master Gardener Program's document: _Garden Notes #214: Estimating Soil Texture_: [https://cmg.extension.colostate.edu/Gardennotes/214.pdf](https://cmg.extension.colostate.edu/Gardennotes/214.pdf)
*   Materials needed for "Soil Particle Demonstration Jar" (instructions in "Garden Notes #214", page 214--3):
    *   Two tall slender jars with lids 
    *   Non-foaming dishwasher detergent
*   "Site Selection Test Questions" handout (attached)
*   "Student Handout: Water Holding Capacity Test" (attached)
*   Materials needed for "Water Holding Capacity Test":
    *   1 plastic 2-liter bottle 
    *   1 measuring cup
    *   1 cup soil
    *   1 cup water
    *   a coffee filter or several cotton balls
-   Video/DVD: *Symphony of the Soil* (Minutes 0:00--7:57):
[https://symphonyofthesoil.com](https://symphonyofthesoil.com). Available for online rental from Vimeo: [https://vimeo.com/ondemand/soilsymphony](https://vimeo.com/ondemand/soilsymphony).
*   Video Clip: *The Monsoon Project* (Minutes 0:00--3:32):
    <div class="embed-responsive embed-responsive-16by9">
    <iframe src="https://www.youtube.com/embed/wCRkLcLT1cE?modestbranding=1&rel=0&start=1&end=212" frameborder="0" gesture="media" showinfo="0" allow="encrypted-media" allowfullscreen></iframe>
    </div>

##### Before You Begin {-}

*   Ensure that at least one educator/instructor/volunteer will be available to supervise each soil test or site selection working group.
*   Educators/instructors/volunteers should prepare themselves to teach about dryland farming as both an ancient and a current planting technique by:
    *   Reading: *Dove Creek Bean Farmers*. Edible Southwest Colorado Magazine: No. 12. Spring/Summer 2013. [http://ediblesouthwestcolorado.com/hello-world/](http://ediblesouthwestcolorado.com/hello-world/)
    *   Watching: 
        *   DVD Clip: _Symphony of the Soil_
        *   Video Clip: _The Monsoon Project_
        *   Video: _Conservation: The Hopi Way_ (4:51 mins) :
            <div class="embed-responsive embed-responsive-16by9">
    <iframe src="https://www.youtube.com/embed/lrEe1l6C1J4?modestbranding=1&rel=0&start=1&end=212" frameborder="0" gesture="media" showinfo="0" allow="encrypted-media" allowfullscreen></iframe>
    </div>
*   Prepare the experiment found in _Garden Notes #214: Estimating Soil Texture_.
    * **One or two days prior to this class**, create a soil particle demonstration jar to use as a prop (the soil takes this long to fully settle). On the jar, mark on the depth of each soil layer type, as described in steps 1–10.
*   Determine some possible sites for the students in Group 2 to choose from, when conducting their soil tests.
*   Consider which areas students in Group 5 might consider when looking for an area to assess.
*   Print water cycle diagram or load for projection.
*   Print _Garden Notes #214: Estimating Soil Texture_.
*   Print 3–5 copies (students can share in pairs) of "Student Handout: Water Holding Capacity Test".
*   Print 5–7 copies (one for each student in this working group) of "Student Handout: Site Selection Selection Questions".
*   Load the video clips.


#### Long Session {-}
***Long Session: Traditional Dryland Farming***

**Format:** One approximately 90 minute session

##### Opening Circle: Questions and Discussion {-}

**Survey students' understanding and/or opinions by verbally sharing the questions or text in italics. Briefly gather input from the students, while steering the discussion toward the answers listed below the question.**

**_Where does soil come from?_**

View the video clip: " The Symphony of Soil": minute 0:00–7:57.

Soil is made of a combination of minerals, organic matter and sand. These three ingredients are combined in different amounts and travel long distances around the globe through the movements of glaciers, water and wind.

**_How does soil gain water? _**

View the video clip: Minute 0:00–3:32 of _The Monsoon Project_

Using the water cycle diagram, help students locate precipitation in the cycle. Water is delivered to the soil in two ways:

*   The Earth's Water Cycle: precipitation in the form of rain, snow and ice. In the Southwest, the most important weather events that deliver water to the soil are winter snowstorms and summer monsoon rains. 
*   Humans capture and store water from the water cycle and spread it on the soil using irrigation systems. 

**_How does soil lose water?_**

Using the water cycle diagram, help students locate **transpiration** and **evaporation** in the cycle.

The soil loses water through a process called **evapotranspiration**. This means the soil loses moisture through direct evaporation and through plant tissues, due to the wind and the sun.

Breaking this term into two parts helps reveal this definition:

*   **Transpiration** — plants sweat out and lose water they have received from the soil
*   **Evaporation** — the soil loses water due to the wind and the sun

To slow this process down, farmers use a technique called **mulching**. Mulch is:

*   a material that is spread over a planting area, protecting the soil from the effects of the wind and the sun.
*   a layer of insulation that traps moisture and shades the soil, preventing  the water in the soil from evaporating. 
*   Carbon-based materials such as straw or dry grass clippings.
*   Pueblo farmers, such as the Hopi, use dust and sand as a mulch; they covered the moist soil that held their seeds with a thick layer of sand and dust. 

**_Why do some farmers apply irrigation water to their soil? _**

Some farmers irrigate because:

*   they are replacing the water that their plants and soil have lost to evapotranspiration.
*   Some plants require more water than the environment has to offer; the farmers apply irrigation water to make up for water that does not arrive in the form of rain and snow.

Some modern farmers do not apply irrigation water to their soil: 

*   Hopi farmers who have vast dryland corn fields 
*   farmers from the western states who have large dryland crop farms.

Hopi and other dryland farmers do not use irrigation systems; the keys to their success is understanding weather patterns, caring for their soil, planting drought-resilient seeds and having faith in natural cycles.

> **_"Dry-farming in the high desert....relying only on precipitation and runoff water, requires an almost miraculous level of faith and is sustained by hard work, prayer, and an attitude of deep humility."_**
> 
> --- <cite>Wall and Masayesva 2004:436</cite>

**_How do dryland farmers decide where to place their gardens and fields? Why is this decision so important? List the following features on the whiteboard, gather student input, and clarify with simple geographic drawings. _**

Choosing the location of a garden is called "site selection". It is important to dryland farming because the chosen site must be able to capture and hold water delivered by the Water Cycle, making it "drought-resilient". 

**These are the features that the ancestral Pueblo farmers of the past and the Hopi dryland farmers of today look for in a site that will be drought-resilient**:

1.  **Geography:** Water that drains off of a mesa or cliff will collect and flood down into drainages, washes, arroyos or canyons. Where these features become less narrow and open up into sandy slopes, Pueblo farmers expect water and  good soil to collect because it is washed down with the floodwaters. This mouth or opening is also a place where they traditionally built **check dams**: rows of low rock walls to slow down the movement of runoff water.
1.  **Garden slope**: North-facing slopes have more shade, therefore less water is lost to evaporation.
1.  **Indicator plants**: The appearance of certain plants in early spring give information, or _indicate_, to Hopi and other Dryland farmers about where the best places are for a garden/field, how deep to plant and how much space to leave between plants. Farmers combine these indications with practice, experience and knowledge of the land. Some examples of plants that indicate these conditions are:

<table>
  <tr>
   <td>
<strong>CONDITION</strong>
   </td>
   <td><strong>INDICATOR PLANT</strong>
   </td>
  </tr>
  <tr>
   <td>Good soil moisture
   </td>
   <td>Rabbitbrush<br>
Four-wing saltbrush<br>
Mormon tea<br>
Rice grass<br>
Snakeweed
   </td>
  </tr>
  <tr>
   <td>Deep, well drained soil
   </td>
   <td>Rabbitbrush<br>
Oak trees
   </td>
  </tr>
</table>

1.  **Soil moisture depth**: deep, soft soils that allows natural reservoirs of water to collect in and be held deep in the soil.
1.  **Soil color**: darker colors often mean higher amounts of decomposed organic matter and nutrients in the soil. In the Southwest, this means dark red-brown.
1.  **Large, open planting area**: the area must be large enough that clumps of seeds can be planted with wide spaces between them (2-3 adult paces/steps or 4 - 6 feet, between clumps.) This spacing allows little soil-moisture reservoirs to be created between clumps, providing long-term moisture. 

**_When a normal amount of snow and rain does not arrive year after year, this is called a "drought"._**

**_How did ancestral Puebloan farmers respond to drought?_**

The Hopi people of today continue to use the agricultural knowledge gained through their ancestral dryland farming practices. They want to ensure their crops will continue to be drought-resilient into the future.**_ _**To survive drought, a dryland farmer must know a lot about their soil and their seeds. Ancestral Pueblo farmers responded to drought by:

*   anticipating the possibility that it could arrive any year, and preparing for it by saving seeds from plants that can survive drought. 
*   using the site selection factors listed above as test questions to decide whether or not a site will be drought-resilient. 
*   meeting these site requirements by planting in multiple locations.
*   using clumps of plants at the edge of the planting area, or tin cans placed around seedlings, as a windbreak to decrease evapotranspiration.
*   Covering holes that contain seeds with loose topsoil to act as a "dust mulch".

**_Do modern dryland farmers use any of these same practices? _**

Yes, however, in modern fields, there is an emphasis on knowing the soil through soil testing:

*   First, farmers learn what is in their soil to determine what kind of soil they have. 
*   Second, farmers find out how much water their soil can hold. If the soil receives more water than it can hold, much of the extra water will drain away. Water that is wasted in this way is called **runoff**; it leads to **erosion**, when soil is carried away by the runoff. 

During this class, we will conduct soil testing experiments as well as practice using the Pueblo farmers' site selection test questions.

##### Procedure {-}

Divide the students into five working groups to complete soil and site selection tests/ experiments. Groups 1–3 will practice using modern soil tests. Groups 3 and 4 will practice using the Puebloan site selection test questions.

**Group 1**: Create a Soil Particle Demonstration jar by following the procedure in _Garden Notes #214: Estimating Soil Texture_, page 214-3.

**Group 2**: Perform Feel, Ball and Ribbon Tests by following the procedure in _Garden Notes #214: Estimating Soil Texture_, page 214-5. Conduct this test in two different locations: one where plant growth is vigorous and one where plant growth is weak. Use the tests to compare and contrast the soil from each site. 

**Group 3**: Perform Water Holding Capacity Test using the attached handout..

**Group 4**: Assess an established growing area, using the Site Selection Test Question Handout using the attached handout. 

**Group 5**: Look for and assess a possible new growing area using the Site Selection Test Question Handout using the attached handout.

##### Closing Circle {-}

**Report-Back**: A representative from each group shares their group's findings. 

**Reflective writing time**: Present two of the three following free-writing topics for students to choose from. Give students 7 - 10 minutes to choose a topic and write a free form answer that reflects who they are/what they value, as a young adult. 

*   Which soil testing methods align most with their worldview?
*   List the ways/reasons they feel connected with corn plants or soil: the shape, appearance, colors? What do you think about, feel or remember when holding corn kernels in your hands or hearing the sound of wind moving through the garden?
*   Hopi corn, and other ancient grains are still grown today because they have survived and grown resiliently through challenging weather, and because humans cared for them and saved their seeds. What makes you resilient? What do you do to make sure you survive through all kinds of weather/situations?

#### Short Session 1 {-}
***Short Session 1: Know Your Soil!***  

**Format:** One approximately 45 minute session

##### Opening Circle: Questions and Discussion {-}

**Survey students' understanding and/or opinions by verbally sharing the questions or text in italics. Briefly gather input from the students, while steering the discussion toward the answers listed below the question.**

**_Where does soil come from?_**

View the video clip: " The Symphony of Soil": minute 0:00–7:57.

Soil is made of a combination of minerals, organic matter and sand. These three ingredients are combined in different amounts and travel long distances around the globe through the movements of glaciers, water and wind.

**_How does soil gain water? _**

View the video clip: Minute 0:00–3:32 of _The Monsoon Project_

Using the water cycle diagram, help students locate precipitation in the cycle. Water is delivered to the soil in two ways:



*   The Earth's Water Cycle: precipitation in the form of rain, snow and ice. In the Southwest, the most important weather events that deliver water to the soil are winter snowstorms and summer monsoon rains. 
*   Humans capture and store water from the water cycle and spread it on the soil using irrigation systems. 

**_How does soil lose water? _**

Using the water cycle diagram, help students locate **transpiration** and **evaporation** in the cycle.

The soil loses water through a process called **evapotranspiration**. This means the soil loses moisture through direct evaporation and through plant tissues, due to the wind and the sun.

Breaking this term into two parts helps reveal this definition:



*   **Transpiration** — plants sweat out and lose water they have received from the soil
*   **Evaporation** — the soil loses water due to the wind and the sun

To slow this process down, farmers use a technique called **mulching**. Mulch is:



*   a material that is spread over a planting area, protecting the soil from the effects of the wind and the sun.
*   a layer of insulation that traps moisture and shades the soil, preventing  the water in the soil from evaporating. 
*   Carbon-based materials such as straw or dry grass clippings.
*   Pueblo farmers, such as the Hopi, use dust and sand as a mulch; they covered the moist soil that held their seeds with a thick layer of sand and dust. 

**_Why do some farmers apply irrigation water to their soil? _**

Some farmers irrigate because:



*   they are replacing the water that their plants and soil have lost to evapotranspiration.
*   Some plants require more water than the environment has to offer; the farmers apply irrigation water to make up for water that does not arrive in the form of rain and snow.

Some modern farmers do not apply irrigation water to their soil: 



*   Hopi farmers who have vast dryland corn fields 
*   farmers from the western states who have large dryland crop farms. 

##### Procedure {-}

Divide the students into working groups of four or five students to complete soil tests/ experiments. 


**Group 1**: Create a Soil Particle Demonstration jar by following the procedure in _Garden Notes #214: Estimating Soil Texture_, page 214-3.


**Group 2**: Perform Feel, Ball and Ribbon Tests by following the procedure in _Garden Notes #214: Estimating Soil Texture_, page 214-5. Conduct this test in two different locations: one where plant growth is vigorous and one where plant growth is weak. Use the tests to compare and contrast the soil from each site. 


**Group 3**: Perform Water Holding Capacity Test using the attached handout.

##### Closing Circle {-}

**Report-Back**: A representative from each group shares their group's findings. 

**Reflective writing time**: If time allows, present the following free-writing topics for students to choose from. Give students 5 - 7 minutes to choose a topic and write a free form answer that reflects who they are/what they value, as a young adult. 

*   Which soil testing methods align most with their worldview?
*   List the ways/reasons they feel connected with corn plants or soil: the shape, appearance, colors? What do you think about, feel or remember when holding corn kernels in your hands or hearing the sound of wind moving through the garden?

#### Short Session 2 {-}
***Short Session 2: Soil and Site Selection***

**Format:** One approximately 45 minute session

##### Opening Circle: Questions and Discussion {-}

Review with students the discussion from the previous day regarding soil and irrigation. Explain that Hopi and other dryland farmers do not use irrigation systems; the keys to their success is understanding weather patterns, caring for their soil, planting drought-resilient seeds and having faith in natural cycles.

**Survey students' understanding and/or opinions by verbally sharing the questions or text in italics. Briefly gather input from the students, while steering the discussion toward the answers listed below the question.**


> **_"Dry-farming in the high desert....relying only on precipitation and runoff water, requires an almost miraculous level of faith and is sustained by hard work, prayer, and an attitude of deep humility."_**
>
> --- <cite>Wall and Masayesva 2004:436</cite>


**_How do dryland farmers decide where to place their gardens and fields? Why is this decision so important? List the following features on the whiteboard, gather student input, and clarify with simple geographic drawings. _**

Choosing the location of a garden is called "site selection". It is important to dryland farming because the chosen site must be able to capture and hold water delivered by the Water Cycle, making it "drought-resilient". 

**These are the features that the ancestral Pueblo farmers of the past and the Hopi dryland farmers of today look for in a site that will be drought-resilient**:

1.  **Geography:** Water that drains off of a mesa or cliff will collect and flood down into drainages, washes, arroyos or canyons. Where these features become less narrow and open up into sandy slopes, Pueblo farmers expect water and  good soil to collect because it is washed down with the floodwaters. This mouth or opening is also a place where they traditionally built **check dams**: rows of low rock walls to slow down the movement of runoff water.
1.  **Garden slope**: North-facing slopes have more shade, therefore less water is lost to evaporation.
1.  **Indicator plants**: The appearance of certain plants in early spring give information, or _indicate_, to Hopi and other Dryland farmers about where the best places are for a garden/field, how deep to plant and how much space to leave between plants. Farmers combine these indications with practice, experience and knowledge of the land. Some examples of plants that indicate these conditions are:

<table>
  <tr>
   <td>
<strong>CONDITION</strong>
   </td>
   <td><strong>INDICATOR PLANT</strong>
   </td>
  </tr>
  <tr>
   <td>Good soil moisture
   </td>
   <td>Rabbitbrush<br>
Four-wing saltbrush<br>
Mormon tea<br>
Rice grass<br>
Snakeweed
   </td>
  </tr>
  <tr>
   <td>Deep, well drained soil
   </td>
   <td>Rabbitbrush<br>
Oak trees
   </td>
  </tr>
</table>

1.  **Soil moisture depth**: deep, soft soils that allows natural reservoirs of water to collect in and be held deep in the soil.
1.  **Soil color**: darker colors often mean higher amounts of decomposed organic matter and nutrients in the soil. In the Southwest, this means dark red-brown.
1.  **Large, open planting area**: the area must be large enough that clumps of seeds can be planted with wide spaces between them (2-3 adult paces/steps or 4 - 6 feet, between clumps.) This spacing allows little soil-moisture reservoirs to be created between clumps, providing long-term moisture. 

**_When a normal amount of snow and rain does not arrive year after year, this is called a "drought"._**

**_How did ancestral Puebloan farmers respond to drought?_**

The Hopi people of today continue to use the agricultural knowledge gained through their ancestral dryland farming practices. They want to ensure their crops will continue to be drought-resilient into the future.**_ _**To survive drought, a dryland farmer must know a lot about their soil and their seeds. Ancestral Pueblo farmers responded to drought by:



*   anticipating the possibility that it could arrive any year, and preparing for it by saving seeds from plants that can survive drought. 
*   using the site selection factors listed above as test questions to decide whether or not a site will be drought-resilient. 
*   meeting these site requirements by planting in multiple locations.
*   using clumps of plants at the edge of the planting area, or tin cans placed around seedlings, as a windbreak to decrease evapotranspiration.
*   Covering holes that contain seeds with loose topsoil to act as a "dust mulch".

**_Do modern dryland farmers use any of these same practices? _**

Yes, however, in modern fields, there is an emphasis on knowing the soil through soil testing:



*   First, farmers learn what is in their soil to determine what kind of soil they have. 
*   Second, farmers find out how much water their soil can hold. If the soil receives more water than it can hold, much of the extra water will drain away. Water that is wasted in this way is called **runoff**; it leads to **erosion**, when soil is carried away by the runoff. 

During this class, we will conduct soil testing experiments as well as practice using the Pueblo farmers' site selection test questions.

##### Procedure {-}

Divide the students into small working groups and assign each group one of the following tasks:


**Group 1**: Assess an established growing area, using the Site Selection Test Question Handout using the attached handout. 


**Group 2**: Look for and assess a possible new growing area using the Site Selection Test Question Handout using the attached handout.

##### Closing Circle {-}

**Report-Back**: A representative from each group shares their group's findings. 

**Reflective writing time**: If time allows, present the following free-writing topic to students. Give students 5–7 minutes to choose a topic and write a free form answer that reflects who they are/what they value, as a young adult. 

**"Hopi corn, and other ancient grains are still grown today because they have survived **

**and grown resiliently through challenging weather, and because humans cared for them **

**and saved their seeds. **

**What makes you resilient? **

**What do you do to make sure you survive through all kinds of weather/situations?"**

#### CO Standards {-}
This lesson plan was designed to align with the following Montezuma School to Farm Project Garden Education Standards and state Of Colorado Academic Standards:

<table>
  <tr>
   <td> 
   </td>
   <td><strong>Montezuma School to Farm Project's Garden Education Standards</strong>
   </td>
   <td><strong>Colorado Academic Standards</strong>
   </td>
  </tr>
  <tr>
   <td>6th
   </td>
   <td>Recognizing nitrogen, carbon, and nutrient cycles at work<br>
Soil ecology: organic and inorganic materials<br>
Ancestral Puebloan Practices<br>
Applied Systems Thinking
   </td>
   <td>Science 1.3, 2.1, 2.2, 3., 3.2, 3.3<br>
Phys Ed 1.2, 3.1, 3.2, 4.1<br>
Health 2.1, 2.4<br>
Math 1.1, 4.1<br>
Social Studies 1.1, 1.2, 2.1, 2.2
   </td>
  </tr>
  <tr>
   <td>7th
   </td>
   <td>Biodiversity benefits nitrogen, carbon and nutrient cycles<br>
Soil ecology: decomposition as a constant element of renewal<br>
Irrigation and water conservation<br>
Sustainable water use practices and devices
   </td>
   <td>Science 1.1, 3.2<br>
Phys Ed 1.1, 3.2, 4.1<br>
Health 2.1<br>
Math 3.1, 3.2<br>
Social Studies 1.1, 2.1, 2.2 
   </td>
  </tr>
  <tr>
   <td>8th
   </td>
   <td>Soil Ecology: soil as the lifeblood on Earth; interconnectedness of soil health and human health<br>
Water Conservation: deep understanding of water as a precious and limited resource<br>
Changing systems: climate and weather in the Southwest
   </td>
   <td>Science 1.3, 2.1, 3.2<br>
Phys Ed 2.1, 2.2, 2.3<br>
Health 2.4<br>
Math 2.1, 2.3, 4.2<br>
Social Studies 2.1
   </td>
  </tr>
</table>


**Further information in regards to the Colorado State Standards may be found [here](https://www.cde.state.co.us/apps/standards/).**
